class Message {
// static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int csid = 1;
  static int child_num = 1;
  static int income_total = 1;
  static int income_type = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int edu_type = 1;
  static int family_type = 1;
  static int house_type = 1;
  static int DAYS_BIRTH = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int DAYS_EMPLOYED = 1;
  static int work_phone = 1;
  static int phone = 1;
  static int email = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int family_size = 1;
  static int begin_month = 1;
  static int credit = 1;
  static int gendercode = 1;
  static int carcode = 1;
  static int realitycode = 1;
  static int income_total1 = 1;
  static int income_total2 = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int income_total3 = 1;
  static int income_total4 = 1;
  static int income_total5 = 1;
  static int income_total6 = 1;
  static int income_total7 = 1;
  static int income_total8 = 1;
  static int income_type1 = 1;
  static int income_type2 = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int income_type3 = 1;
  static int income_type4 = 1;
  static int income_type5 = 1;
  static int edu_type1 = 1;
  static int edu_type2 = 1;
  static int edu_type3 = 1;
  static int edu_type4 = 1;
  static int edu_type5 = 1;
  static int family_type1 = 1;
  static int family_type2 = 1;
  static int family_type3 = 1;
  static int family_type4 = 1;
  static int family_type5 = 1; // static은 인스턴스 안만들고 직접 쓸수있게 해준당
  static int house_type1 = 1;
  static int house_type2 = 1;
  static int house_type3 = 1;
  static int house_type4 = 1;
  static int house_type5 = 1;
  static int house_type6 = 1;
}
